export default {
    // 为了避免重复，所以放在一个文件里管理
    CART_AMOUNT_INCREMENT:'CART_AMOUNT_INCREMENT', // 商品加
    CART_AMOUNT_DECREMENT:'CART_AMOUNT_DECREMENT', // 商品减
    START_FETCH_BLOG_LIST:'START_FETCH_BLOG_LIST', // 开始请求列表
    FETCH_BLOG_LIST_SUCCESS:'FETCH_BLOG_LIST_SUCCESS', // 请求列表成功
    FETCH_BLOG_LIST_FAILED:'FETCH_BLOG_LIST_FAILED', // 请求列表失败

}